'use client';

// Renders an HTML string to a base64 PDF, for attaching to outgoing emails
// (see app/api/orders/[id]/email/route.js). Browser-only.
//
// This intentionally does NOT use html-to-image's toPng()/toBlob() convenience
// wrappers - they wait on a requestAnimationFrame internally, which some
// automated/headless browser contexts never fire, hanging forever. Doing the
// steps manually (serialize to SVG, load as an Image, draw to canvas) is also
// what html2canvas-based approaches failed to do reliably: html2canvas
// reimplements CSS layout from scratch and produced blank/broken pages on
// content mixing flex and float. html-to-image instead serializes the DOM
// into an SVG <foreignObject> and lets the real browser rasterize it, so it
// renders exactly what's on screen.
export async function htmlToPdfBase64(html) {
  const htmlToImage = await import('html-to-image');
  const { jsPDF } = await import('jspdf');

  const element = document.createElement('div');
  element.innerHTML = html;
  // Kept on-screen at real coordinates (not top:-9999px) - off-screen elements
  // can't be measured/rendered reliably - but tucked behind the real UI with a
  // negative z-index so it's invisible to the user.
  element.style.position = 'fixed';
  element.style.top = '0';
  element.style.left = '0';
  element.style.zIndex = '-1';
  element.style.pointerEvents = 'none';
  // Pin an explicit width instead of relying on shrink-to-fit sizing for a
  // fixed-position element with no left/right pair - that left content
  // clipped on the right in RTL layouts. Height stays auto (grows with
  // content); the html generated by the email route caps its card at
  // max-width:800px with 20px outer padding, so 840px comfortably fits it.
  element.style.width = '840px';
  document.body.appendChild(element);

  let svgDataUrl;
  try {
    svgDataUrl = await htmlToImage.toSvg(element, { backgroundColor: '#ffffff' });
  } finally {
    document.body.removeChild(element);
  }

  const img = new Image();
  await new Promise((resolve, reject) => {
    img.onload = resolve;
    img.onerror = () => reject(new Error('נכשלה טעינת תמונת ה-PDF'));
    img.src = svgDataUrl;
  });

  // Use the actually-rendered image's own pixel dimensions everywhere below -
  // measuring the source element's offsetWidth/Height separately and reusing
  // those numbers to size the PDF risked a mismatch that cropped content.
  const { naturalWidth: width, naturalHeight: height } = img;
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  canvas.getContext('2d').drawImage(img, 0, 0);
  const pngDataUrl = canvas.toDataURL('image/png');

  // Size the PDF page to the content itself (no A4 pagination) so the whole
  // document fits on one continuous page.
  const pdf = new jsPDF({ unit: 'px', format: [width, height], hotfixes: ['px_scaling'] });
  pdf.addImage(pngDataUrl, 'PNG', 0, 0, width, height);
  return pdf.output('datauristring').split(',')[1];
}
