// תרחישי לשונית התשלומים (W4) להרתמה: נתונים + API מדומה ל-/api/nedarim, /api/payments, /api/refunds, /api/admin/recalculations.
// נטען ע"י entry.jsx (שתי שורות שם). כל תרחיש מבוסס על נתוני הבסיס של העיצוב (530 ₪ = 150+120+140+משלוח 80+דמי ביטול 40).

// base = {ORDER, ITEMS, OBL, PAY, ORG1, ORG2}
export function payScenarios({ ITEMS, OBL, PAY, ORG1, ORG2 }) {
  const neveNoSummary = ORG2.filter(([k]) => k !== 'enable_order_edit_summary_confirm');
  const withExtra = [...neveNoSummary, ['allow_additional_payment_on_order', 'true']];
  // דמי הביטול של הפריט שהוסר לפני 2 דקות - חלון הזיכוי (15 דק׳ כברירת מחדל) פעיל → "ניתן לזכות ₪40 על פריט חדש עוד mm:ss" (R39)
  const recentItems = ITEMS.map(i => (i.id === 'a4' ? { ...i, deletedAt: new Date(Date.now() - 120e3).toISOString() } : i));
  const dated = OBL.map((o, k) => ({ ...o, createdAt: `2026-09-23T07:1${k}:00.000Z` }));
  const refund = { id: 'r1', amount: 120, reason: 'יתרת זכות אוטומטית - הזמנה #53375', isAutoGenerated: true, isExecuted: false, isDeleted: false, bankName: 'דיסקונט', bankBranch: '123', bankAccount: '4567', bankAccountName: 'מרים אברמוביץ', createdAt: '2026-09-24T08:00:00.000Z' };
  return {
    // לשונית התשלומים כמו בעיצוב (מאוזן, זיכוי ממתין עם פרטי בנק, ספירה בשורת דמי הביטול)
    pay: { settings: withExtra, items: recentItems, obligations: dated, refunds: [refund] },
    // זיכוי אוטומטי בלי פרטי בנק → "הזנת פרטי בנק" → D4b עם IBAN
    paybank: { settings: withExtra, obligations: dated, refunds: [{ ...refund, bankName: '', bankBranch: '', bankAccount: '', bankAccountName: '' }] },
    // חוב קיים 230 ₪ (תשלום אחד) → "תשלום ₪230" → D3 עם 4 שיטות (נדרים + תשלום נוסף)
    paydebt: { settings: withExtra, items: recentItems, obligations: dated, payments: [PAY[0]], refunds: [refund] },
    // שמירה שיוצרת חוב חדש (השרת מוסיף חיוב) → debtCreated → D3 "השינויים נשמרו! נוצר חיוב חדש" עם "השאר חוב"
    paysave: { draft: true, settings: withExtra, obligations: dated, putAddsCharge: true },
    // הגמ"ח הראשי, יתרת זכות בלי זיכוי ממתין → "זכה ₪N" → בקשת זיכוי (בלי אישור - כמו בישן)
    paycredit: { settings: ORG1, order: { isDelivery: false, deliveryDirection: null, deliveryCity: null }, obligations: dated.filter(o => o.id !== 'ob4'), payments: [{ ...PAY[0] }, { ...PAY[1], amount: 300 }] },
  };
}

const NEW_CHARGE = { id: 'ob9', amount: 120, description: 'השכרת שמלה דגם 5120 מידה 40 (פריט #a9)', orderItemId: 'a9', isManual: false, isDeleted: false, createdAt: '2026-10-04T08:00:00.000Z' };

/** מחזיר Response לנתיבי הכסף, או null. ctx = {S, order, j, body} */
export function payMock(u, method, ctx) {
  const { S, order, j } = ctx;
  const body = ctx.body ? JSON.parse(ctx.body) : null;
  if (u === '/api/nedarim' && method === 'POST') {
    if (String(body.cardNumber || '').startsWith('4000')) return j({ success: false, error: 'הכרטיס נדחה (הדגמה)' });
    return j({ success: true, confirmation: '0123456', rawResponse: JSON.stringify({ Status: 'OK', Confirmation: '0123456', LastNum: String(body.cardNumber).slice(-4) }) });
  }
  if (u === '/api/payments' && method === 'POST') return j({ id: `np${Date.now()}`, orderId: 53375, amount: body.amount, paymentMethod: body.paymentMethod, notes: body.notes, isDeleted: false, paymentDate: new Date().toISOString() });
  if (u === '/api/refunds' && method === 'POST') return j({ id: 'r9', ...body }, 201);
  if (/^\/api\/refunds\/[^/]+$/.test(u) && method === 'PUT') return j({ id: u.split('/').pop(), ...body });
  if (u === '/api/admin/recalculations' && method === 'POST') return j({ success: true, appliedCount: 1, successIds: body.orderIds, errors: [] });
  if (S.putAddsCharge && /^\/api\/orders\/53375$/.test(u) && method === 'PUT') {
    return j({ ...order, ...body, customer: order.customer, items: order.items, obligations: [...order.obligations, NEW_CHARGE], payments: order.payments, refunds: order.refunds || [], updatedAt: new Date().toISOString() });
  }
  return null;
}
