import { pathToFileURL } from 'node:url';
const m = await import(pathToFileURL(process.env.PROJ + '/lib/ai/aiCommon.js').href);
let pass = 0, fail = 0;
const eq = (name, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); ok ? pass++ : fail++; console.log((ok ? 'PASS ' : 'FAIL ') + name + (ok ? '' : '\n   got : ' + JSON.stringify(got) + '\n   want: ' + JSON.stringify(want))); };
const N = m.normalizeAiSql;
eq('status NOT IN', N(`WHERE O."status" NOT IN ('טיוטה', 'שמור לחיוב')`), `WHERE COALESCE(O."status", '') NOT IN ('טיוטה', 'שמור לחיוב')`);
eq('status NOT IN idempotent', N(N(`WHERE "status" NOT IN ('a')`)), `WHERE COALESCE("status", '') NOT IN ('a')`);
eq('status <>', N(`AND "status" <> 'x'`), `AND COALESCE("status", '') <> 'x'`);
eq('eventDate =', N(`"eventDate" = '2026-09-22'`), `("eventDate" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date = '2026-09-22'`);
eq('alias >=', N(`O."eventDate" >= '2026-08-14' AND O."eventDate" <= '2026-09-11'`), `(O."eventDate" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date >= '2026-08-14' AND (O."eventDate" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date <= '2026-09-11'`);
eq('::date cast', N(`O."returnDate"::date = '2026-09-19'`), `(O."returnDate" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date = '2026-09-19'`);
eq('DATE()', N(`DATE("orderDate") = '2026-09-15'`), `(“orderDate” AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date = '2026-09-15'`.replace(/[“”]/g, '"'));
eq('BETWEEN', N(`"eventDate" BETWEEN '2026-01-01' AND '2026-01-31'`), `("eventDate" AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Jerusalem')::date BETWEEN '2026-01-01' AND '2026-01-31'`);
eq('idempotent dates', N(N(`"eventDate" = '2026-09-22'`)), N(`"eventDate" = '2026-09-22'`));
eq('no touch: now()', N(`"eventDate" >= now()`), `"eventDate" >= now()`);
eq('no touch: EXTRACT', N(`EXTRACT(YEAR FROM "eventDate") = 2024`), `EXTRACT(YEAR FROM "eventDate") = 2024`);
eq('no touch: other col', N(`"createdAt" = '2026-01-01'`), `"createdAt" = '2026-01-01'`);
const now = new Date('2026-09-20T09:00:00Z'); // 12:00 Israel, ט' בתשרי (9 Tishrei 5787)
const F = (t) => m.fixDatePairsInText(t, now);
eq('pair ok', F('י"א בתשרי תשפ"ז (22/09/2026)'), 'י"א בתשרי תשפ"ז (22/09/2026)');
eq('pair wrong greg -> fix from hebrew', F('י"א בתשרי תשפ"ז (12/10/2026)'), 'י"א בתשרי תשפ"ז (22/09/2026)');
eq('pair wrong hebrew of today -> fix hebrew', F('י"ז באלול תשפ"ו (20/09/2026)'), 'ט\' בתשרי תשפ"ז (20/09/2026)');
eq('pair ד׳ + ״', F('ד׳ בתשרי תשפ״ז (15/09/2026)'), 'ד׳ בתשרי תשפ״ז (15/09/2026)');
eq('range', F('מ-א\' באלול תשפ"ו (14/08/2026) ועד כ"ט באלול תשפ"ו (11/09/2026)'), 'מ-א\' באלול תשפ"ו (14/08/2026) ועד כ"ט באלול תשפ"ו (11/09/2026)');
eq('hist: cheshvan wrong greg', F('כ"ה בחשוון תשפ"ה (26/10/2024)'), 'כ"ה בחשוון תשפ"ה (26/11/2024)');
eq('hist: elul 22 vs 15/09', F('כ"ב באלול תשפ"ו (15/09/2026)'), 'כ"ב באלול תשפ"ו (04/09/2026)'.replace('04/09','04/09'));
eq('no date -> untouched', F('שלום עולם'), 'שלום עולם');
eq('sanitize sandbox link', m.sanitizeAiText('ניתן להוריד [הורדת קובץ אקסל](sandbox:/mnt/data/x.xlsx) עכשיו'), 'ניתן להוריד  עכשיו');
eq('sanitize SQL line', m.sanitizeAiText('האם תרצה?\nSQL: SELECT 1\nתודה'), 'האם תרצה?\nתודה');
eq('sanitize md', m.sanitizeAiText('**חשוב** \n* ראשון\n* שני'), 'חשוב \n- ראשון\n- שני');
const cat = [{ key: 'inventory_buffer_days', category: 'יומן' }, { key: 'enable_deliveries', category: 'משלוחים' }];
eq('setting key fix', m.validateSettingTags('הגדרות מערכת ← הזמנות. ערך 2.\n[OPEN_SETTING:INVENTORY_BUFFER]', cat), 'הגדרות מערכת ← יומן. ערך 2.\n[OPEN_SETTING:inventory_buffer_days]');
eq('setting key invalid dropped', m.validateSettingTags('טקסט\n[OPEN_SETTING:nonexistent_thing]', cat), 'טקסט');
eq('setting exact key kept', m.validateSettingTags('[OPEN_SETTING:enable_deliveries]', cat), '[OPEN_SETTING:enable_deliveries]');
const how = [{ route: '/orders', title: 'הוספת תיקון' }];
eq('link ok', m.validateLinkTags('[OPEN_LINK:/orders|שם אחר]', how), '[OPEN_LINK:/orders|הוספת תיקון]');
eq('link invalid', m.validateLinkTags('x [OPEN_LINK:/nope|nope]', how), 'x');
const r = m.buildAuditRanges(new Date('2026-09-19T22:41:00Z')); // 01:41 Sep 20 Israel
eq('audit yesterday (IL)', r.yesterday, { start: '2026-09-18T21:00:00.000Z', end: '2026-09-19T20:59:59.999Z' });
eq('audit today (IL)', r.today, { start: '2026-09-19T21:00:00.000Z', end: '2026-09-20T20:59:59.999Z' });
const t = m.getIsraelNow(new Date('2026-09-19T22:41:00Z'));
eq('israel now after midnight', [t.iso, t.dmy, t.time, t.weekday], ['2026-09-20', '20/09/2026', '01:41', 'יום ראשון']);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
