// lib/creditOffset.js - קיזוז זיכוי פתוח של לקוחה מחיוב חדש (דיווח 679a860b, נווה יעקב). מודול טהור אחד: בלי imports, בלי DB, בלי React -
// נטען גם בדפדפן (הדפים הישנים) וגם בשרת, ונבדק ב-node רגיל (scripts/test_credit_offset.mjs).
//
// המודל ב-DB (לא משתנה כאן):
//   - "זיכוי פתוח" של הזמנה = בקשת Refund אוטומטית (isAutoGenerated) שממתינה (לא בוצעה, לא נמחקה) = שולם פחות נדרש
//     (lib/creditRefundSync.js syncPendingCreditRefund). החזר שבוצע כבר הפך לתשלום שלילי בהזמנה, ולכן אינו זיכוי פתוח.
//   - קיזוז = שני תשלומים זהים בסכום ובסימן הפוך באותו אמצעי תשלום ייעודי: +X בהזמנה שיש בה חוב, -X בהזמנה שיש בה זיכוי.
//     סכום התשלומים של הלקוחה נשאר אותו דבר, ולכן לוח הבקרה (סכום כולל וגם לפי אמצעי תשלום) לא סופר את זה כמזומן.
//   - בקשות זיכוי ידניות (שעובד פתח) לא מקוזזות: הכסף כבר הובטח להחזר בבנק.

export const CREDIT_OFFSET_SETTING = 'customer_credit_offset_prompt';
export const CREDIT_OFFSET_METHOD = 'קיזוז זיכוי';

export const round2 = (n) => Math.round(((Number(n) || 0) + Number.EPSILON) * 100) / 100;
const live = (rows) => (Array.isArray(rows) ? rows.filter((r) => r && !r.isDeleted) : []);
const sum = (rows) => live(rows).reduce((s, r) => s + (Number(r.amount) || 0), 0);

/** הנדרש לפי אותה נוסחה של syncPendingCreditRefund: totalAmount אם חיובי, אחרת סכום ההתחייבויות. */
export function orderRequiredAmount(order) {
  const obligations = sum(order && order.obligations);
  return order && order.totalAmount && order.totalAmount > 0 ? order.totalAmount : obligations;
}
export const orderPaidAmount = (order) => sum(order && order.payments);

/**
 * חוב הזמנה לקיזוז. שתי הנוסחאות שבשימוש בקוד (totalAmount-קודם של השרת, סכום התחייבויות של הכרטיס) חייבות להסכים שיש חוב -
 * לוקחים את הקטן מבין השניים, כדי שלעולם לא נכסה יותר ממה שחסר, וכדי שהקיזוז לא יהפוך את ההזמנה עצמה ליתרת זכות.
 */
export function orderDebt(order) {
  if (!order) return 0;
  const paid = orderPaidAmount(order);
  const byServer = round2(orderRequiredAmount(order) - paid);
  const byObligations = round2(sum(order.obligations) - paid);
  const hasObligations = live(order.obligations).length > 0;
  const debt = hasObligations ? Math.min(byServer, byObligations) : byServer;
  return debt > 0.004 ? round2(debt) : 0;
}

/**
 * זיכוי פתוח של הזמנה אחת, או null. כלל: הבקשה האוטומטית הממתינה, אבל לא יותר מיתרת הזכות בפועל מעבר לבקשות ידניות פתוחות
 * (בדיוק neededAuto של syncPendingCreditRefund). הזמנה מחוקה, או בלי בקשה אוטומטית ממתינה (למשל הזמנה ישנה שהוחזרה באקסס) = אין זיכוי.
 */
export function orderOpenCredit(order, { includeDeleted = false } = {}) {
  if (!order) return null;
  if (order.isDeleted && !includeDeleted) return null;
  const refunds = live(order.refunds).filter((r) => !r.isExecuted);
  const auto = refunds.filter((r) => r.isAutoGenerated).reduce((s, r) => s + (Number(r.amount) || 0), 0);
  if (auto <= 0.004) return null;
  const manualOpen = refunds.filter((r) => !r.isAutoGenerated).reduce((s, r) => s + (Number(r.amount) || 0), 0);
  const ledger = round2(orderPaidAmount(order) - orderRequiredAmount(order) - manualOpen);
  const amount = round2(Math.min(auto, ledger));
  if (amount <= 0.004) return null;
  return { orderId: order.orderId, amount, orderDate: order.orderDate || null };
}

const dateKey = (d) => {
  const t = d ? new Date(d).getTime() : NaN;
  return Number.isFinite(t) ? t : Infinity;
};

/**
 * תכנית קיזוז לפי המצב כפי שנטען. target = ההזמנה עם החוב; others = שאר הזמנות אותה לקוחה.
 * מהישן לחדש (תאריך הזמנה, ואז מספר הזמנה). maxAmount (לא חובה) = התקרה שהעובד/ה ראו בשאלה.
 * @returns {{debt:number, available:number, offsetAmount:number, sources:{orderId:number, amount:number, available:number}[], excluded:{orderId:number, reason:string}[]}}
 */
export function planCreditOffset({ target, others = [], maxAmount } = {}) {
  const empty = { debt: 0, available: 0, offsetAmount: 0, sources: [], excluded: [] };
  if (!target || target.isDeleted || !target.customerId) return empty;
  const debt = orderDebt(target);
  const excluded = [];
  const credits = [];
  for (const o of others || []) {
    if (!o || o.orderId === target.orderId) continue;
    if (o.customerId !== target.customerId) { excluded.push({ orderId: o.orderId, reason: 'לקוחה אחרת' }); continue; }
    if (o.isDeleted) { excluded.push({ orderId: o.orderId, reason: 'הזמנה מחוקה' }); continue; }
    const c = orderOpenCredit(o);
    if (!c) { excluded.push({ orderId: o.orderId, reason: 'אין זיכוי פתוח' }); continue; }
    credits.push(c);
  }
  credits.sort((a, b) => (dateKey(a.orderDate) - dateKey(b.orderDate)) || (a.orderId - b.orderId));
  const available = round2(credits.reduce((s, c) => s + c.amount, 0));
  const cap = maxAmount === undefined || maxAmount === null ? Infinity : Math.max(0, round2(maxAmount));
  let left = Math.min(debt, available, cap);
  const offsetAmount = left > 0.004 ? round2(left) : 0;
  const sources = [];
  left = offsetAmount;
  for (const c of credits) {
    if (left <= 0.004) break;
    const take = round2(Math.min(c.amount, left));
    if (take <= 0.004) continue;
    sources.push({ orderId: c.orderId, amount: take, available: c.amount });
    left = round2(left - take);
  }
  return { debt, available, offsetAmount, sources, excluded };
}

const money = (n) => `₪${round2(n).toLocaleString('he-IL')}`;

/** השאלה היחידה שנשאלת בשמירה (נוסח הבעלים). X = כל הזיכוי הפתוח, #Y = ההזמנה/ות שממנה/ן הוא. */
export function offsetQuestion(plan) {
  if (!plan || !(plan.offsetAmount > 0)) return '';
  const all = (plan.sources || []).map((s) => `#${s.orderId}`);
  const from = all.length <= 1 ? `מהזמנה ${all[0] || ''}`.trim() : `מהזמנות ${all.join(', ')}`;
  let text = `ללקוחה יש זיכוי פתוח של ${money(plan.available)} ${from}. לקזז מהחוב?`;
  if (plan.offsetAmount + 0.004 < plan.available) text += `\nיקוזזו ${money(plan.offsetAmount)} (כל החוב), והיתרה תישאר זיכוי פתוח לפעם הבאה.`;
  else if (plan.offsetAmount + 0.004 < plan.debt) text += `\nיקוזזו ${money(plan.offsetAmount)}, ויישארו לתשלום ${money(plan.debt - plan.offsetAmount)}.`;
  return text;
}

// ---- סימון הזוג בהערת התשלום (נשאר קריא למי שרואה את ההערה בכרטיס) ----
const MARK = (key) => `[קיזוז:${key}]`;
const UNDO_MARK = (key) => `[ביטול-קיזוז:${key}]`;
export const pairKeyOf = (requestKey, sourceOrderId) => `${requestKey}.${sourceOrderId}`;
export const requestMarker = (requestKey) => `[קיזוז:${requestKey}.`; // תחילת כל הזוגות של בקשה אחת (לבדיקת כפילות)
export const undoMarker = UNDO_MARK;

const PAIR_RE = /\[קיזוז:([A-Za-z0-9_-]+\.\d+)\]/;
export const parsePairKey = (notes) => ((String(notes || '').match(PAIR_RE) || [])[1] || null);
export const isOffsetPayment = (p) => !!p && !p.isDeleted && p.paymentMethod === CREDIT_OFFSET_METHOD;
export const isValidRequestKey = (k) => typeof k === 'string' && /^[A-Za-z0-9_-]{8,64}$/.test(k);

/**
 * שורות התשלום שנכתבות בטרנזקציה אחת: לכל מקור זוג (+X בהזמנה עם החוב, -X בהזמנה עם הזיכוי).
 * שני הצדדים isRefund=false כדי שסכום אותו אמצעי תשלום בלוח הבקרה יהיה אפס בדיוק (ולא פרוסת "קיזוז" חיובית בלי מקבילה שלילית).
 */
export function buildOffsetRows({ plan, target, sourceCustomers = {}, requestKey }) {
  const rows = [];
  for (const s of (plan && plan.sources) || []) {
    const key = pairKeyOf(requestKey, s.orderId);
    rows.push({
      orderId: target.orderId, customerId: target.customerId, amount: s.amount,
      paymentMethod: CREDIT_OFFSET_METHOD, isRefund: false,
      notes: `קיזוז זיכוי מהזמנה #${s.orderId} ${MARK(key)}`,
    });
    rows.push({
      orderId: s.orderId, customerId: sourceCustomers[s.orderId] || target.customerId, amount: -s.amount,
      paymentMethod: CREDIT_OFFSET_METHOD, isRefund: false,
      notes: `קיזוז זיכוי לטובת הזמנה #${target.orderId} ${MARK(key)}`,
    });
  }
  return rows;
}

/**
 * ביטול קיזוז כשההזמנה שקוזז לתוכה נמחקה: לכל זוג שעוד לא בוטל - תנועות הפוכות (לא מוחקים תשלומים, ההיסטוריה נשמרת).
 * @param {{offsetRows: object[], undoneKeys: string[]}} p  offsetRows = כל תשלומי הקיזוז (שני צדי הזוגות) שלא נמחקו; undoneKeys = זוגות שכבר בוטלו
 */
export function buildReversalRows({ offsetRows = [], undoneKeys = [] }) {
  const undone = new Set(undoneKeys);
  const rows = [];
  for (const p of offsetRows) {
    if (!isOffsetPayment(p)) continue;
    const key = parsePairKey(p.notes);
    if (!key || undone.has(key)) continue;
    rows.push({
      orderId: p.orderId, customerId: p.customerId || null, amount: round2(-(Number(p.amount) || 0)),
      paymentMethod: CREDIT_OFFSET_METHOD, isRefund: false,
      notes: `ביטול קיזוז זיכוי ${UNDO_MARK(key)}`,
    });
  }
  return rows;
}
