import prisma, { auditAs } from '@/app/lib/prisma';

const round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;

/**
 * יוצר או מעדכן "החזר אשראי" אוטומטי שמשקף את יתרת הזכות (התשלום העודף) של ההזמנה
 * מול סך התחייבויותיה. רץ אחרי כל שינוי תשלום/התחייבות.
 */
export async function syncPendingCreditRefund(orderId) {
  const numericOrderId = parseInt(orderId);
  if (isNaN(numericOrderId)) return;

  // B4: שליפה לפני הטרנזקציה — ה-TX מחזיק רק כתיבות (פחות זמן חסימת חיבור מול Neon)
  const order = await prisma.order.findUnique({
    where: { orderId: numericOrderId },
    select: {
      orderId: true,
      customerId: true,
      totalAmount: true,
      payments: { where: { isDeleted: false }, select: { amount: true } },
      obligations: { where: { isDeleted: false }, select: { amount: true } },
      customer: { select: { bankName: true, bankBranch: true, bankAccount: true, bankAccountName: true } }
    }
  });
  if (!order) return;

  const totalPaid = order.payments.reduce((sum, p) => sum + p.amount, 0);
  const obligationsSum = order.obligations.reduce((sum, o) => sum + o.amount, 0);
  const totalRequired = (order.totalAmount && order.totalAmount > 0) ? order.totalAmount : obligationsSum;
  const credit = round2(totalPaid - totalRequired);

  const openRefunds = await prisma.refund.findMany({
    where: { orderId: numericOrderId, isDeleted: false, isExecuted: false }
  });
  const existingAuto = openRefunds.find(r => r.isAutoGenerated) || null;
  const otherOpenTotal = openRefunds
    .filter(r => r.id !== existingAuto?.id)
    .reduce((sum, r) => sum + r.amount, 0);

  const neededAuto = Math.max(0, round2(credit - otherOpenTotal));

  await prisma.$transaction(async (tx) => {
    if (neededAuto <= 0) {
      if (existingAuto) {
        await tx.refund.update(auditAs('AUTO_CREDIT_REFUND_CLEARED', {
          where: { id: existingAuto.id },
          data: { isDeleted: true }
        }));
      }
      return;
    }

    if (existingAuto) {
      if (Math.abs(existingAuto.amount - neededAuto) > 0.01) {
        await tx.refund.update(auditAs('AUTO_CREDIT_REFUND_UPDATED', {
          where: { id: existingAuto.id },
          data: { amount: neededAuto }
        }));
      }
      return;
    }

    await tx.refund.create(auditAs('AUTO_CREDIT_REFUND_CREATED', {
      data: {
        customerId: order.customerId,
        orderId: numericOrderId,
        amount: neededAuto,
        reason: `יתרת זכות אוטומטית - הזמנה #${numericOrderId}`,
        isAutoGenerated: true,
        bankName: order.customer?.bankName || null,
        bankBranch: order.customer?.bankBranch || null,
        bankAccount: order.customer?.bankAccount || null,
        bankAccountName: order.customer?.bankAccountName || null
      }
    }));
  }, { timeout: 15000, maxWait: 10000 });
}
