import prisma, { auditAs } from '@/app/lib/prisma';

const round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;

/**
 * שומר על שורת "בקשת זיכוי" אוטומטית ומסונכרנת בטאב "זיכויים ממתינים" כל עוד להזמנה
 * יש יתרת זכות (שולם יותר משנדרש) שאין לה כבר כיסוי מבקשת זיכוי ידנית פתוחה.
 * נקרא מכל נקודה שמשנה totalPaid/totalRequired של הזמנה - ר' lib/pricingEngine.js
 * ו-app/api/payments/route.js.
 */
export async function syncPendingCreditRefund(orderId) {
  const numericOrderId = parseInt(orderId);
  if (isNaN(numericOrderId)) return;

  await prisma.$transaction(async (tx) => {
    const order = await tx.order.findUnique({
      where: { orderId: numericOrderId },
      select: {
        orderId: true,
        customerId: true,
        totalAmount: true,
        payments: { where: { isDeleted: false }, select: { amount: true } },
        obligations: { where: { isDeleted: false }, select: { amount: true } },
        customer: { select: { bankName: true, bankBranch: true, bankAccount: true, bankAccountName: true } }
      }
    });
    if (!order) return;

    const totalPaid = order.payments.reduce((sum, p) => sum + p.amount, 0);
    const obligationsSum = order.obligations.reduce((sum, o) => sum + o.amount, 0);
    // אותו fallback הקיים כבר במקומות אחרים (למשל debt-approval/route.js): totalAmount
    // המפורש אם קיים וחיובי, אחרת סכום ההתחייבויות.
    const totalRequired = (order.totalAmount && order.totalAmount > 0) ? order.totalAmount : obligationsSum;
    const credit = round2(totalPaid - totalRequired);

    const openRefunds = await tx.refund.findMany({
      where: { orderId: numericOrderId, isDeleted: false, isExecuted: false }
    });
    const existingAuto = openRefunds.find(r => r.isAutoGenerated) || null;
    const otherOpenTotal = openRefunds
      .filter(r => r.id !== existingAuto?.id)
      .reduce((sum, r) => sum + r.amount, 0);

    // לא מכפילים זיכוי שכבר יש לו בקשה ידנית פתוחה מכסה אותו.
    const neededAuto = Math.max(0, round2(credit - otherOpenTotal));

    if (neededAuto <= 0) {
      if (existingAuto) {
        await tx.refund.update(auditAs('AUTO_CREDIT_REFUND_CLEARED', {
          where: { id: existingAuto.id },
          data: { isDeleted: true }
        }));
      }
      return;
    }

    if (existingAuto) {
      if (Math.abs(existingAuto.amount - neededAuto) > 0.01) {
        await tx.refund.update(auditAs('AUTO_CREDIT_REFUND_UPDATED', {
          where: { id: existingAuto.id },
          data: { amount: neededAuto }
        }));
      }
      return;
    }

    await tx.refund.create(auditAs('AUTO_CREDIT_REFUND_CREATED', {
      data: {
        customerId: order.customerId,
        orderId: numericOrderId,
        amount: neededAuto,
        reason: `יתרת זכות אוטומטית - הזמנה #${numericOrderId}`,
        isAutoGenerated: true,
        bankName: order.customer?.bankName || null,
        bankBranch: order.customer?.bankBranch || null,
        bankAccount: order.customer?.bankAccount || null,
        bankAccountName: order.customer?.bankAccountName || null
      }
    }));
  }, { timeout: 15000, maxWait: 10000 });
}
