// lib/creditOffsetServer.js - הצד שכותב של קיזוז זיכוי (ר' lib/creditOffset.js לכללים). prisma ו-syncPendingCreditRefund מוזרקים (DI) כדי
// שאפשר לבדוק את כל הזרימה ב-node רגיל מול DB בזיכרון (scripts/test_credit_offset.mjs); הנתיב app/api/orders/[id]/credit-offset/route.js
// והמחיקה ב-app/api/orders/[id]/route.js מעבירים את הלקוח האמיתי. הכרטיס החדש (a5) יכול לקרוא לאותו נתיב.
//
// כללי כתיבה (ר' זיכרון "No reads inside Prisma transactions" ו-"No manual AuditLog writes"):
//   - כל הקריאות הכבדות (הזמנות הלקוחה) לפני הטרנזקציה; בתוכה רק נעילה + 1+N סכומי תשלומים אינדקסיים קטנים + הכתיבות.
//   - אין כתיבת AuditLog ידנית: תוסף היומן ב-app/lib/prisma.js רושם כל create של Payment.
import {
  CREDIT_OFFSET_METHOD, planCreditOffset, buildOffsetRows, buildReversalRows, isValidRequestKey, requestMarker, undoMarker, parsePairKey, round2,
} from './creditOffset.js';

const LOCK_NAMESPACE = 7314; // מפתח נעילה ראשון של pg_advisory_xact_lock (השני = מספר ההזמנה)
const TX_OPTIONS = { timeout: 15000, maxWait: 10000 };

const ORDER_SELECT = {
  orderId: true, customerId: true, orderDate: true, isDeleted: true, totalAmount: true,
  payments: { where: { isDeleted: false }, select: { amount: true } },
  obligations: { where: { isDeleted: false }, select: { amount: true } },
  refunds: { where: { isDeleted: false }, select: { id: true, amount: true, isExecuted: true, isAutoGenerated: true, isDeleted: true } },
};

/** טוען את ההזמנה עם החוב ואת הזמנות אותה לקוחה שיש בהן בקשת זיכוי אוטומטית ממתינה (הועמדות היחידות שיכולות להיות מקור). */
export async function loadOffsetContext(prisma, orderId) {
  const target = await prisma.order.findUnique({ where: { orderId }, select: ORDER_SELECT });
  if (!target || !target.customerId) return { target: target || null, others: [] };
  const others = await prisma.order.findMany({
    where: {
      customerId: target.customerId, isDeleted: false, orderId: { not: orderId },
      refunds: { some: { isDeleted: false, isExecuted: false, isAutoGenerated: true } },
    },
    select: ORDER_SELECT,
  });
  return { target, others };
}

export async function previewCreditOffset(prisma, orderId, { maxAmount } = {}) {
  const { target, others } = await loadOffsetContext(prisma, orderId);
  if (!target) return { found: false, plan: null };
  return { found: true, target, plan: planCreditOffset({ target, others, maxAmount }) };
}

const paidOf = async (tx, orderId) => {
  const r = await tx.payment.aggregate({ where: { orderId, isDeleted: false }, _sum: { amount: true } });
  return round2((r && r._sum && r._sum.amount) || 0);
};
const loadedPaid = (order) => round2((order.payments || []).reduce((s, p) => s + (Number(p.amount) || 0), 0));

/**
 * מבצע את הקיזוז. סדר: תכנית מהמצב הנטען -> טרנזקציה (נעילה לפי מספרי הזמנה בסדר עולה, בדיקת כפילות לפי requestKey,
 * בדיקה שסכומי התשלומים לא השתנו מאז הטעינה, כתיבת הזוגות) -> אחריה סנכרון בקשות הזיכוי של כל ההזמנות שנגעו בהן.
 * לחיצה כפולה: הקריאה השנייה (אותו requestKey) מקבלת duplicate; בלי requestKey - החוב כבר קוזז ולכן אין מה לקזז, ובמרוץ בין שתי
 * קריאות בו-זמניות בדיקת הסכומים בתוך הנעילה עוצרת את השנייה (STALE).
 * @returns {Promise<{status:'applied'|'nothing'|'duplicate'|'stale'|'not_found', plan?:object, amount?:number, sources?:object[], syncFailed?:number[]}>}
 */
export async function applyCreditOffset({ prisma, orderId, maxAmount, requestKey, syncPendingCreditRefund, grantsHold }) {
  const { target, others } = await loadOffsetContext(prisma, orderId);
  if (!target) return { status: 'not_found' };
  const plan = planCreditOffset({ target, others, maxAmount });
  if (!(plan.offsetAmount > 0)) {
    // ייתכן שזו לחיצה כפולה שהקריאה הראשונה שלה כבר קיזזה (החוב אפס) - אם יש סימון של אותו requestKey, מדווחים duplicate
    if (isValidRequestKey(requestKey)) {
      const done = await prisma.payment.findFirst({ where: { orderId, isDeleted: false, paymentMethod: CREDIT_OFFSET_METHOD, notes: { contains: requestMarker(requestKey) } }, select: { id: true } });
      if (done) return { status: 'duplicate', plan };
    }
    return { status: 'nothing', plan };
  }
  const key = isValidRequestKey(requestKey) ? requestKey : null;
  const effectiveKey = key || `srv${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
  const byId = new Map(others.map((o) => [o.orderId, o]));
  const rows = buildOffsetRows({ plan, target, sourceCustomers: Object.fromEntries(others.map((o) => [o.orderId, o.customerId])), requestKey: effectiveKey });
  const lockIds = [orderId, ...plan.sources.map((s) => s.orderId)].sort((a, b) => a - b);
  const expectedPaid = new Map([[orderId, loadedPaid(target)], ...plan.sources.map((s) => [s.orderId, loadedPaid(byId.get(s.orderId))])]);

  const outcome = await prisma.$transaction(async (tx) => {
    for (const id of lockIds) await tx.$queryRawUnsafe(`SELECT pg_advisory_xact_lock(${LOCK_NAMESPACE}, ${Number(id)})`);
    if (key) {
      const dup = await tx.payment.findFirst({ where: { orderId, isDeleted: false, paymentMethod: CREDIT_OFFSET_METHOD, notes: { contains: requestMarker(key) } }, select: { id: true } });
      if (dup) return 'duplicate';
    }
    for (const id of lockIds) {
      if ((await paidOf(tx, id)) !== expectedPaid.get(id)) return 'stale';
    }
    for (const data of rows) await tx.payment.create({ data });
    return 'applied';
  }, TX_OPTIONS);

  if (outcome !== 'applied') return { status: outcome, plan };

  const syncFailed = [];
  for (const id of lockIds) {
    try { await syncPendingCreditRefund(id); } catch (e) { syncFailed.push(id); console.error(`credit offset: syncPendingCreditRefund(${id}) failed after commit`, e && e.message); }
  }
  // כסף נכנס להזמנה (כמו POST /api/payments): פריטי עגלה ממתינים הופכים לשמורים
  if (grantsHold) {
    try { await grantsHold(orderId, plan.offsetAmount); } catch (e) { console.error('credit offset: confirming cart items failed after commit', e && e.message); }
  }
  return { status: 'applied', plan, amount: plan.offsetAmount, sources: plan.sources, syncFailed };
}

/**
 * הזמנה שנמחקה (DELETE /api/orders/[id]) שקוזז לתוכה זיכוי: מחזירים את הזיכוי להזמנה המקורית בתנועות הפוכות.
 * בלי זה הכסף נשאר "תקוע" בהזמנה המחוקה בלי בקשת זיכוי (אותה בעיה ידועה של תשלום רגיל בהזמנה שנמחקת, דיווח c00b42cf).
 * בלי קיזוזים בהזמנה - לא קורה כלום. חוזר { reversed: מספר זוגות }.
 */
export async function reverseCreditOffsetsForOrder({ prisma, orderId, syncPendingCreditRefund }) {
  const mine = await prisma.payment.findMany({
    where: { orderId, isDeleted: false, paymentMethod: CREDIT_OFFSET_METHOD, amount: { gt: 0 } },
    select: { id: true, notes: true },
  });
  const keys = [...new Set(mine.map((p) => parsePairKey(p.notes)).filter(Boolean))];
  if (!keys.length) return { reversed: 0 };
  const pairRows = await prisma.payment.findMany({
    where: { isDeleted: false, paymentMethod: CREDIT_OFFSET_METHOD, OR: keys.map((k) => ({ notes: { contains: `[קיזוז:${k}]` } })) },
    select: { id: true, orderId: true, customerId: true, amount: true, notes: true, paymentMethod: true, isDeleted: true },
  });
  const undoneRows = await prisma.payment.findMany({
    where: { isDeleted: false, paymentMethod: CREDIT_OFFSET_METHOD, OR: keys.map((k) => ({ notes: { contains: undoMarker(k) } })) },
    select: { notes: true },
  });
  const undoneKeys = keys.filter((k) => undoneRows.some((r) => String(r.notes || '').includes(undoMarker(k))));
  const rows = buildReversalRows({ offsetRows: pairRows, undoneKeys });
  if (!rows.length) return { reversed: 0 };
  await prisma.$transaction(async (tx) => {
    for (const data of rows) await tx.payment.create({ data });
  }, TX_OPTIONS);
  // ההזמנה שנמחקה עצמה לא מסונכרנת: סנכרון היה פותח לה בקשת זיכוי על תשלומים אחרים שבה (שינוי התנהגות שאינו חלק מהקיזוז)
  const touched = [...new Set(rows.map((r) => r.orderId))].filter((id) => id !== orderId);
  for (const id of touched) {
    try { await syncPendingCreditRefund(id); } catch (e) { console.error(`credit offset reversal: syncPendingCreditRefund(${id}) failed`, e && e.message); }
  }
  return { reversed: keys.length - undoneKeys.length };
}
