// app/v3/strings/he.js — מילון המחרוזות (CONSTITUTION §ה... §ב.6/§ט.2, LIBRARY-MAP §3).
// מפתח: <אזור>.<רכיב/מסך>.<תפקיד> (אזורים: common, nav, order, customer, dress,
// rental, payment, dialog, notice, error, tip). ערך: עברית, נכתב מחדש (R10) —
// לא מועתק מהאתר הישן. פרמטרים: {name}. ריבוי: _one/_other.
//
// זהו מקור-ברירת-המחדל בלבד. override לפי ארגון מגיע מ-LabelsContext הקיים
// (/api/settings/labels) - t()/useStrings ב-index.js משלבים את שתי השכבות.
// מפתח חסר כאן = שגיאת build/גלריה (§ט.2) - כל מפתח שנקרא חייב שורה כאן.

const he = {
  // common
  'common.action.save': 'שמירה',
  'common.action.cancel': 'ביטול',
  'common.action.confirm': 'אישור',
  'common.action.close': 'סגירה',
  'common.action.back': 'חזרה',
  'common.action.next': 'המשך',
  'common.action.edit': 'עריכה',
  'common.action.delete': 'מחיקה',
  'common.action.undo': 'ביטול השינוי',
  'common.action.redo': 'החזר ביטול',
  'common.action.discardAll': 'ביטול כל השינויים',
  'common.state.missing': 'חסר',
  'common.state.saved': 'נשמר',
  'common.state.unsaved': 'לא נשמר',
  'common.state.loading': 'טוען…',
  'common.state.empty.title': 'לא נמצאו תוצאות',
  'common.state.empty.action': 'נקה סינון',

  // dialog (LayerManager)
  'dialog.confirm.defaultTitle': 'לאשר את הפעולה?',
  'dialog.confirm.confirmLabel': 'אישור',
  'dialog.confirm.cancelLabel': 'ביטול',
  'dialog.code.title': 'נדרש אישור מנהל',
  'dialog.code.approverLabel': 'מאשר/ת',
  'dialog.code.pinLabel': 'קוד אישור',
  'dialog.busy.default': 'רק רגע…',

  // notice / toast
  'notice.saved.default': 'השינויים נשמרו',
  'notice.action.open': 'פתיחה',
  'toast.info.done': 'הפעולה בוצעה',

  // order (רייל/מנוע שינויים - שימוש עתידי, Phase 3+)
  'order.rail.title': 'שינויים בהזמנה',
  'order.rail.empty': 'אין שינויים שלא נשמרו',
  'order.rail.netCharge': 'לתשלום אחרי שמירה',
  'order.rail.netCredit': 'לזיכוי אחרי שמירה',

  // customer (הפיילוט - archetype detail card)
  'customer.card.title': 'כרטיס לקוחה',
  'customer.card.glance': 'במבט אחד',
  'customer.card.tab.details': 'פרטים',
  'customer.card.tab.orders': 'הזמנות',
  'customer.card.tab.payments': 'תשלומים',
  'customer.card.tab.history': 'היסטוריה',
  'customer.field.fullName': 'שם מלא',
  'customer.field.phone1': 'טלפון',
  'customer.field.phone2': 'טלפון נוסף',
  'customer.field.email': 'דוא"ל',
  'customer.field.address': 'כתובת',
  'customer.field.idNumber': 'תעודת זהות',
  'customer.field.notes': 'הערות',
  'customer.status.blocked': 'לקוחה חסומה',
  'customer.status.debt': 'יתרת חוב',
  'customer.status.credit': 'זיכוי ממתין',
  'customer.status.ok': 'אין חוב פתוח',

  // customer — פיילוט v3 של כרטיס הלקוח (app/v3/pilot/customer, route /v3-pilot/customers/[id]).
  // נכתב מחדש לפי אב-הטיפוס שנסקר (docs/redesign-v3/prototypes/REVIEW-1/2); לא מועתק מהעמוד הישן.
  'customer.page.kind': 'כרטיס לקוח',
  'customer.page.newKind': 'לקוחות',
  'customer.page.newTitle': 'לקוח חדש',
  'customer.page.noName': 'לקוח בלי שם',
  'customer.page.number': 'מספר {n}',
  'customer.page.noNumber': 'ללא מספר לקוח',
  'customer.page.orders_one': 'הזמנה אחת',
  'customer.page.orders_other': '{n} הזמנות',
  'customer.page.blocked': 'חסום להזמנות',
  'customer.page.updated': 'עודכן {when}',
  'customer.page.updatedTip': 'מתי נשמר שינוי אחרון בפרטי הלקוח',
  'customer.page.back': 'חזרה',
  'customer.page.backTip': 'חזרה לעמוד הקודם',
  'customer.page.mail': 'מייל ללקוח',
  'customer.page.mailTip': 'שליחת מייל ללקוח (דורש אישור מנהל)',
  'customer.page.loading': 'טוענים את פרטי הלקוח…',
  'customer.page.loadError': 'לא הצלחנו לטעון את הלקוח',
  'customer.page.loadErrorText': 'ייתכן שיש בעיית חיבור. אפשר לנסות שוב, או לחזור לרשימה.',
  'customer.page.retry': 'לנסות שוב',
  'customer.page.toList': 'לרשימת הלקוחות',
  'customer.tab.label': 'לשוניות הכרטיס',
  'customer.tab.details': 'פרטים',
  'customer.tab.orders': 'הזמנות',
  'customer.tab.payments': 'תשלומים',
  'customer.tab.refunds': 'זיכוי ובנק',
  'customer.tab.history': 'היסטוריה',
  'customer.tab.unsaved': 'יש כאן שינוי שלא נשמר',
  'customer.tab.debt': 'יש חוב',

  'customer.field.firstName': 'שם פרטי',
  'customer.field.lastName': 'שם משפחה',
  'customer.field.city': 'עיר',
  'customer.field.street': 'רחוב',
  'customer.field.houseNum': 'מספר בית',
  'customer.field.zeout': 'תעודת זהות',
  'customer.field.marketingConsent': 'דיוור',
  'customer.field.bankName': 'שם הבנק',
  'customer.field.bankBranch': 'סניף בנק',
  'customer.field.bankAccount': 'מספר חשבון',
  'customer.field.bankAccountName': 'בעל החשבון',
  'customer.field.notesLong': 'הערות על הלקוח',
  'customer.field.zeoutTip': 'משמשת לזיהוי הלקוח כשמשנים או מבטלים הזמנה.',
  'customer.field.zeoutPh': '9 ספרות',
  'customer.field.bankNamePh': 'לדוגמה: לאומי',
  'customer.field.bankBranchPh': 'מספר הסניף',
  'customer.consent.on': 'מאשר/ת לקבל עדכונים ודיוור',
  'customer.consent.yes': 'מאשר/ת לקבל עדכונים',
  'customer.consent.no': 'לא מאשר/ת',
  'customer.value.empty': 'ריק',
  'customer.value.was': 'היה: {v}',
  'customer.value.unsaved': 'לא נשמר',

  'customer.details.title': 'פרטי קשר',
  'customer.details.editTitle': 'עריכת פרטים',
  'customer.details.tip': 'השינויים נאספים ברשימה שבצד. שום דבר לא נשמר עד שלוחצים "שמירת השינויים".',
  'customer.details.edit': 'עריכה',
  'customer.details.saveAndClose': 'שמירה וסיום עריכה',
  'customer.details.noContactTitle': 'אין פרטי קשר',
  'customer.details.noContactText': 'לחצו "עריכה" כדי להוסיף טלפון, מייל או כתובת.',
  'customer.details.copy': 'העתקה',
  'customer.details.copied': 'הכתובת הועתקה',
  'customer.details.sendMail': 'שליחת מייל',
  'customer.details.gmail': 'השלמה ל-@gmail.com',
  'customer.details.gmailTip': 'מוסיף את הסיומת לסוף מה שהוקלד',
  'customer.details.save': 'שמירת השינויים',
  'customer.notes.title': 'הערות',
  'customer.notes.tip': 'שורות עם הסימן "אוטומטי" נכתבות מעצמן כשקורה משהו בהזמנה.',
  'customer.notes.auto': 'אוטומטי',
  'customer.notes.modelSize': 'דגם {model} · מידה {size}',
  'customer.notes.openOrder': 'הזמנה {id}',

  'customer.block.title': 'הלקוח חסום להזמנות חדשות',
  'customer.block.unblock': 'ביטול החסימה',
  'customer.block.onlyHead': 'ביטול החסימה: להנהלה',
  'customer.block.onlyHeadTip': 'רק הנהלה ראשית יכולה לבטל חסימה',
  'customer.block.confirmTitle': 'לבטל את החסימה?',
  'customer.block.confirmText': 'הלקוח יוכל שוב לקבל הזמנות חדשות.',
  'customer.block.keep': 'השארת החסימה',
  'customer.block.done': 'החסימה בוטלה',
  'customer.block.failed': 'החסימה לא בוטלה',
  'customer.block.networkError': 'אין חיבור לשרת. נסו שוב.',

  'customer.orders.title': 'ההזמנות של הלקוח',
  'customer.orders.tip': 'לחיצה על שורה פותחת את ההזמנה. החץ מציג סכומים.',
  'customer.orders.col.order': 'הזמנה',
  'customer.orders.col.date': 'תאריך',
  'customer.orders.col.status': 'מצב',
  'customer.orders.link': 'הזמנה {id}',
  'customer.orders.pickup': 'לקיחה {d}',
  'customer.orders.return': 'החזרה {d}',
  'customer.orders.required': 'לחיוב',
  'customer.orders.paid': 'שולם',
  'customer.orders.payStatus': 'מצב תשלום',
  'customer.orders.emptyTitle': 'עדיין אין הזמנות',
  'customer.orders.emptyText': 'הזמנות של הלקוח יופיעו כאן, מהחדשה לישנה.',
  'customer.orders.count': '{n} הזמנות',

  'customer.pay.accountTitle': 'מצב החשבון',
  'customer.pay.required': 'סך החיובים',
  'customer.pay.paid': 'סך התשלומים',
  'customer.pay.refunded': 'סך הזיכויים',
  'customer.pay.debt': 'הלקוח חייב',
  'customer.pay.credit': 'זכות ללקוח',
  'customer.pay.even': 'החשבון מאוזן',
  'customer.pay.formula': 'היתרה = חיובים, פחות תשלומים, ועוד כל הזיכויים (גם אלה שעוד ממתינים לביצוע).',
  'customer.pay.listTitle': 'תשלומים וזיכויים',
  'customer.pay.listTip': 'החץ בכל שורה מציג לאיזו הזמנה היא שייכת ואיך שולם.',
  'customer.pay.col.date': 'תאריך',
  'customer.pay.col.type': 'סוג',
  'customer.pay.col.amount': 'סכום',
  'customer.pay.type.payment': 'תשלום',
  'customer.pay.type.refund': 'זיכוי',
  'customer.pay.order': 'הזמנה',
  'customer.pay.method': 'אמצעי תשלום',
  'customer.pay.reason': 'סיבה',
  'customer.pay.note': 'הערה',
  'customer.pay.noNote': 'אין הערה',
  'customer.pay.exec': 'ביצוע',
  'customer.pay.executed': 'בוצע {d}',
  'customer.pay.pending': 'ממתין לביצוע',
  'customer.pay.emptyTitle': 'עדיין אין תשלומים',
  'customer.pay.emptyText': 'תשלומים וזיכויים מכל ההזמנות יופיעו כאן.',
  'customer.pay.count': '{n} רשומות',

  'customer.refunds.bankTitle': 'חשבון בנק להחזרים',
  'customer.refunds.bankTip': 'לשם מעבירים כסף כשהלקוח מקבל זיכוי. נשמר יחד עם שאר השינויים בכרטיס.',
  'customer.refunds.listTitle': 'זיכויים ללקוח',
  'customer.refunds.col.requested': 'בקשה',
  'customer.refunds.col.order': 'הזמנה',
  'customer.refunds.col.amount': 'סכום',
  'customer.refunds.col.state': 'מצב',
  'customer.refunds.done': 'בוצע',
  'customer.refunds.waiting': 'ממתין',
  'customer.refunds.emptyTitle': 'אין זיכויים',
  'customer.refunds.emptyText': 'זיכוי שנפתח בהזמנה של הלקוח יופיע כאן.',
  'customer.refunds.count': '{n} זיכויים',

  'customer.history.title': 'שינויים בפרטי הלקוח',
  'customer.history.tip': 'כאן מופיעים שינויים בפרטי הלקוח עצמו ומיילים שנשלחו אליו. תשלומים ושינויים בהזמנות מופיעים בכרטיס ההזמנה.',
  'customer.history.loading': 'טוענים את ההיסטוריה…',
  'customer.history.error': 'לא הצלחנו לטעון את ההיסטוריה',

  'customer.rail.label': 'סיכום ושינויים',
  'customer.rail.glance': 'במבט אחד',
  'customer.rail.orders': 'הזמנות',
  'customer.rail.debt': 'חוב',
  'customer.rail.credit': 'זכות',
  'customer.rail.balance': 'יתרה',
  'customer.rail.upcoming': 'ההזמנה הקרובה',
  'customer.rail.noUpcoming': 'אין הזמנה קרובה',
  'customer.rail.state': 'מצב',
  'customer.rail.changes': 'שינויים שלא נשמרו',
  'customer.rail.changesTip': 'כל שורה היא שינוי אחד. אפשר לבטל שינוי בודד ולהחזיר אותו. "שמירת השינויים" שומרת את כולם יחד.',
  'customer.rail.empty': 'אין שינויים. כל עריכה תופיע כאן.',
  'customer.rail.added': '{field} נוסף',
  'customer.rail.changed': '{field} שונה',
  'customer.rail.undoneLine': 'השינוי בוטל · אפשר להחזיר',
  'customer.rail.undo': 'ביטול השינוי ב{field}',
  'customer.rail.undoTip': 'ביטול השינוי הזה בלבד',
  'customer.rail.redo': 'החזרת השינוי ב{field}',
  'customer.rail.redoTip': 'החזרת השינוי שבוטל',
  'customer.rail.save': 'שמירת השינויים',
  'customer.rail.saving': 'שומרים…',
  'customer.rail.discard': 'ביטול כל השינויים',
  'customer.rail.discardTitle': 'לבטל את כל השינויים?',
  'customer.rail.discardText': '{n} שינויים יימחקו והכרטיס יחזור למצב השמור.',
  'customer.rail.keep': 'להשאיר את השינויים',
  'customer.rail.discarded': 'השינויים בוטלו',
  'customer.rail.undone': 'השינוי ב{field} בוטל',
  'customer.rail.undoneText': 'אפשר להחזיר אותו מהרשימה',
  'customer.rail.bar_zero': 'אין שינויים',
  'customer.rail.bar_other': '{n} שינויים שלא נשמרו',
  'customer.rail.barSave': 'שמירה',

  'customer.save.done': 'הפרטים נשמרו',
  'customer.save.created': 'הלקוח נוצר',
  'customer.save.cantYet': 'אי אפשר לשמור עדיין',
  'customer.save.failed': 'השמירה לא הצליחה',
  'customer.save.conflictTitle': 'מישהו אחר עדכן את הלקוח',
  'customer.save.conflictRefresh': 'רענון הכרטיס',
  'customer.save.notNow': 'לא עכשיו',
  'customer.save.fieldsToFix': '{n} שדות צריכים תיקון',
  'customer.save.required': 'צריך למלא',
  'customer.save.groupMissing': 'צריך למלא אחד מאלה: {fields}',
  'customer.save.generic': 'שגיאה בשמירה. נסו שוב.',

  'customer.exit.title': 'יש שינויים שלא נשמרו',
  'customer.exit.text': 'מה לעשות איתם לפני שיוצאים?',
  'customer.exit.save': 'שמירה ויציאה',
  'customer.exit.drop': 'יציאה בלי לשמור',
  'customer.exit.stay': 'להישאר בכרטיס',

  'customer.new.title': 'פרטי הלקוח',
  'customer.new.tip': 'לכל הזמנה צריך שתי דרכים ליצור קשר: טלפון, ועוד טלפון או מייל.',
  'customer.new.optional': '(לא חובה)',
  'customer.new.create': 'יצירת הלקוח',
  'customer.new.creating': 'יוצרים…',

  'customer.mail.noMailTitle': 'ללקוח אין מייל',
  'customer.mail.noMailText': 'קודם מוסיפים כתובת מייל ושומרים, ואז אפשר לשלוח.',
  'customer.mail.addMail': 'הוספת מייל',
  'customer.mail.approvePurpose': 'שליחת מייל ללקוח צריכה אישור של מנהל.',
  'customer.mail.title': 'מייל ל{name}',
  'customer.mail.to': 'יישלח אל',
  'customer.mail.subject': 'נושא',
  'customer.mail.body': 'תוכן ההודעה',
  'customer.mail.files': 'קבצים',
  'customer.mail.filesTip': 'אפשר לבחור כמה קבצים. טבלת הוראות מצורפת מעצמה.',
  'customer.mail.pickFiles': 'בחירת קבצים',
  'customer.mail.noFiles': 'לא נבחרו קבצים',
  'customer.mail.pickedFiles': 'נבחרו {n} קבצים: {names}',
  'customer.mail.dest': 'איך לשלוח את הקבצים',
  'customer.mail.dest.email': 'בתוך המייל',
  'customer.mail.dest.drive': 'קישור מהדרייב',
  'customer.mail.dest.both': 'שניהם',
  'customer.mail.folder': 'תיקייה בדרייב',
  'customer.mail.folderPh': 'מזהה התיקייה',
  'customer.mail.folderHint': 'הנמען יוכל להוריד את הקבצים.',
  'customer.mail.send': 'שליחה',
  'customer.mail.sending': 'שולחים…',
  'customer.mail.close': 'סגירה (הטיוטה נשמרת)',
  'customer.mail.clear': 'ניקוי הטיוטה',
  'customer.mail.clearTitle': 'לנקות את הטיוטה?',
  'customer.mail.clearText': 'הנושא, התוכן והקבצים שבחרתם יימחקו.',
  'customer.mail.keep': 'להשאיר',
  'customer.mail.required': 'צריך למלא נושא ותוכן.',
  'customer.mail.sent': 'המייל נשלח.',
  'customer.mail.sentDrive': 'המייל נשלח. {n} קבצים שותפו בדרייב להורדה.',
  'customer.mail.autoClose': 'החלון ייסגר מעצמו.',
  'customer.mail.failed': 'המייל לא נשלח.',
  'customer.mail.networkError': 'אין חיבור לשרת. הטיוטה נשמרה — אפשר לנסות שוב.',
  'customer.mail.sentToast': 'המייל נשלח',
  'customer.mail.sentToastText': 'אל {name}',

  'approve.title': 'אישור מנהל',
  'approve.who': 'מי מאשר',
  'approve.whoTip': 'רק עובדים שמורשים לאשר את הפעולה הזו מופיעים ברשימה.',
  'approve.search': 'חיפוש לפי שם',
  'approve.me': '{name} (אני)',
  'approve.loading': 'טוענים את רשימת המאשרים…',
  'approve.none': 'אין עובד שמורשה לאשר את זה. אפשר להגדיר מאשרים בעמוד ההרשאות.',
  'approve.notFound': 'לא נמצא עובד בשם הזה',
  'approve.password': 'הסיסמה של המאשר',
  'approve.show': 'הצגת הסיסמה',
  'approve.hide': 'הסתרת הסיסמה',
  'approve.pickFirst': 'צריך לבחור מי מאשר',
  'approve.typePassword': 'צריך להקליד סיסמה',
  'approve.checking': 'בודקים…',
  'approve.wrong': 'הסיסמה לא נכונה, או שהעובד לא פעיל.',
  'approve.network': 'אין חיבור לשרת. נסו שוב.',

  // tip (הסברים)
  'tip.customer.idNumber': 'תעודת הזהות מוצגת לעובדי הנהלה בלבד ומשמשת לאימות זהות.',
  'tip.customer.blocked': 'לקוחה חסומה לא יכולה לפתוח הזמנה חדשה עד שההגבלה תוסר.',
};

export default he;
