// בדיקות קיזוז זיכוי פתוח מחוב חדש (דיווח 679a860b, נווה יעקב): lib/creditOffset.js (טהור), lib/creditOffsetServer.js (מול DB בזיכרון, עם סנכרון
// בקשות הזיכוי מומחש כמו lib/creditRefundSync.js), lib/creditOfferClient.js (fetch/אישור מוזרקים), ובדיקות מבנה סטטיות (הגדרה כבויה כברירת מחדל,
// נתיב, מחיקת הזמנה, הדפים הישנים). בלי DB אמיתי, בלי שרת, בלי כתיבה.
// הרצה (מהשורש): node scripts/test_credit_offset.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CREDIT_OFFSET_METHOD, CREDIT_OFFSET_SETTING, planCreditOffset, orderDebt, orderOpenCredit, offsetQuestion, buildOffsetRows, buildReversalRows,
  parsePairKey, isValidRequestKey, pairKeyOf, round2,
} from '../lib/creditOffset.js';
import { applyCreditOffset, reverseCreditOffsetsForOrder, previewCreditOffset } from '../lib/creditOffsetServer.js';
import { offerCreditOffset } from '../lib/creditOfferClient.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/\r\n/g, '\n');

let passed = 0;
let failed = 0;
async function t(name, fn) {
  try { await fn(); passed++; console.log('  ok   -', name); } catch (e) { failed++; process.exitCode = 1; console.error('  FAIL -', name, '\n        ', e.stack || e.message); }
}

// ---------------------------------------------------------------- DB בזיכרון
let seq = 0;
function makeDb({ orders = [], payments = [], refunds = [] } = {}) {
  const db = { orders: orders.map((o) => ({ isDeleted: false, totalAmount: null, obligations: [], orderDate: null, ...o })), payments: payments.map((p) => ({ id: `p${++seq}`, isDeleted: false, isRefund: false, paymentMethod: 'מזומן', notes: '', ...p })), refunds: refunds.map((r) => ({ id: `r${++seq}`, isDeleted: false, isExecuted: false, isAutoGenerated: false, ...r })), txCount: 0, lockCalls: [], failOnCreate: 0, creates: 0 };
  const shape = (o) => ({
    orderId: o.orderId, customerId: o.customerId, orderDate: o.orderDate, isDeleted: o.isDeleted, totalAmount: o.totalAmount,
    obligations: o.obligations.filter((x) => !x.isDeleted).map((x) => ({ amount: x.amount })),
    payments: db.payments.filter((p) => p.orderId === o.orderId && !p.isDeleted).map((p) => ({ amount: p.amount })),
    refunds: db.refunds.filter((r) => r.orderId === o.orderId && !r.isDeleted).map((r) => ({ ...r })),
  });
  const matchPay = (p, w) => {
    if (w.orderId !== undefined && p.orderId !== w.orderId) return false;
    if (w.isDeleted !== undefined && p.isDeleted !== w.isDeleted) return false;
    if (w.paymentMethod !== undefined && p.paymentMethod !== w.paymentMethod) return false;
    if (w.amount && w.amount.gt !== undefined && !(p.amount > w.amount.gt)) return false;
    if (w.notes && w.notes.contains !== undefined && !String(p.notes || '').includes(w.notes.contains)) return false;
    if (w.OR && !w.OR.some((c) => matchPay(p, c))) return false;
    return true;
  };
  const client = {
    order: {
      async findUnique({ where }) { const o = db.orders.find((x) => x.orderId === where.orderId); return o ? shape(o) : null; },
      async findMany({ where }) {
        return db.orders.filter((o) => o.customerId === where.customerId && o.isDeleted === where.isDeleted && o.orderId !== where.orderId.not
          && db.refunds.some((r) => r.orderId === o.orderId && !r.isDeleted && !r.isExecuted && r.isAutoGenerated)).map(shape);
      },
    },
    payment: {
      async findFirst({ where }) { return db.payments.find((p) => matchPay(p, where)) || null; },
      async findMany({ where }) { return db.payments.filter((p) => matchPay(p, where)).map((p) => ({ ...p })); },
      async aggregate({ where }) { return { _sum: { amount: db.payments.filter((p) => matchPay(p, where)).reduce((s, p) => s + p.amount, 0) } }; },
      async create({ data }) {
        db.creates++;
        if (db.failOnCreate && db.creates === db.failOnCreate) throw new Error('boom');
        const row = { id: `p${++seq}`, isDeleted: false, isRefund: false, notes: '', ...data };
        db.payments.push(row);
        return { ...row };
      },
    },
    _tail: Promise.resolve(),
    $transaction(fn) {
      // ה-DB האמיתי מסדר טרנזקציות על אותן נעילות; כאן מסדרים את כולן בתור (מספיק לבדיקת המרוץ)
      const run = async () => {
        db.txCount++;
        const snapshot = db.payments.map((p) => ({ ...p }));
        try {
          return await fn({ ...client, $queryRawUnsafe: async (sql) => { db.lockCalls.push(sql); return []; } });
        } catch (e) {
          db.payments.length = 0; db.payments.push(...snapshot); // rollback
          throw e;
        }
      };
      const p = client._tail.then(run, run);
      client._tail = p.catch(() => {});
      return p;
    },
  };
  db.client = client;
  // כמו lib/creditRefundSync.js (אותה נוסחה): בקשת זיכוי אוטומטית = שולם פחות נדרש פחות בקשות ידניות פתוחות
  db.sync = async (orderId) => {
    const o = db.orders.find((x) => x.orderId === orderId);
    const paid = db.payments.filter((p) => p.orderId === orderId && !p.isDeleted).reduce((s, p) => s + p.amount, 0);
    const obl = o.obligations.filter((x) => !x.isDeleted).reduce((s, x) => s + x.amount, 0);
    const required = o.totalAmount && o.totalAmount > 0 ? o.totalAmount : obl;
    const credit = round2(paid - required);
    const open = db.refunds.filter((r) => r.orderId === orderId && !r.isDeleted && !r.isExecuted);
    const auto = open.find((r) => r.isAutoGenerated);
    const other = open.filter((r) => r !== auto).reduce((s, r) => s + r.amount, 0);
    const needed = Math.max(0, round2(credit - other));
    if (needed <= 0) { if (auto) auto.isDeleted = true; return; }
    if (auto) auto.amount = needed;
    else db.refunds.push({ id: `r${++seq}`, orderId, customerId: o.customerId, amount: needed, isAutoGenerated: true, isDeleted: false, isExecuted: false });
  };
  return db;
}

const ord = (orderId, required, extra = {}) => ({ orderId, customerId: 'c1', obligations: [{ amount: required }], orderDate: `2026-09-${String(10 + orderId % 15).padStart(2, '0')}T08:00:00Z`, ...extra });
const pay = (orderId, amount, extra = {}) => ({ orderId, customerId: 'c1', amount, ...extra });
const autoRefund = (orderId, amount, extra = {}) => ({ orderId, customerId: 'c1', amount, isAutoGenerated: true, ...extra });
const paidOf = (db, orderId) => round2(db.payments.filter((p) => p.orderId === orderId && !p.isDeleted).reduce((s, p) => s + p.amount, 0));
const openAuto = (db, orderId) => db.refunds.filter((r) => r.orderId === orderId && r.isAutoGenerated && !r.isDeleted && !r.isExecuted);
const apply = (db, orderId, opts = {}) => applyCreditOffset({ prisma: db.client, orderId, syncPendingCreditRefund: db.sync, ...opts });

// תרחיש בסיס: הזמנה 2 (חוב) והזמנה 1 (זיכוי פתוח)
const scenario = ({ debt = 100, credit = 150 } = {}) => makeDb({
  orders: [ord(1, 100), ord(2, debt)],
  payments: [pay(1, 100 + credit)],
  refunds: [autoRefund(1, credit)],
});

console.log('lib/creditOffset.js - כללי התכנית (טהור)');
await t('זיכוי אחד מכסה את כל החוב בדיוק', () => {
  const plan = planCreditOffset({ target: { ...ord(2, 150), payments: [], refunds: [] }, others: [{ ...ord(1, 100), payments: [{ amount: 250 }], refunds: [autoRefund(1, 150)] }] });
  assert.equal(plan.offsetAmount, 150);
  assert.deepEqual(plan.sources.map((s) => [s.orderId, s.amount]), [[1, 150]]);
});
await t('קיזוז חלקי: הזיכוי קטן מהחוב - מקזזים את כל הזיכוי ונשאר חוב', () => {
  const plan = planCreditOffset({ target: { ...ord(2, 180), payments: [], refunds: [] }, others: [{ ...ord(1, 100), payments: [{ amount: 190 }], refunds: [autoRefund(1, 90)] }] });
  assert.equal(plan.offsetAmount, 90);
  assert.equal(plan.debt, 180);
});
await t('הזיכוי גדול מהחוב: מקזזים רק את החוב והיתרה נשארת (לא נבלעת)', () => {
  const plan = planCreditOffset({ target: { ...ord(2, 60), payments: [], refunds: [] }, others: [{ ...ord(1, 100), payments: [{ amount: 250 }], refunds: [autoRefund(1, 150)] }] });
  assert.equal(plan.offsetAmount, 60);
  assert.equal(plan.available, 150);
  assert.equal(plan.sources[0].amount, 60);
});
await t('החזר שבוצע לא נחשב: תשלום שלילי קיים + בקשה שבוצעה = אין זיכוי פתוח', () => {
  const executedPaid = { ...ord(1, 100), payments: [{ amount: 200 }, { amount: -100 }], refunds: [{ ...autoRefund(1, 100), isExecuted: true }] };
  assert.equal(orderOpenCredit(executedPaid), null);
  const plan = planCreditOffset({ target: { ...ord(2, 80), payments: [], refunds: [] }, others: [executedPaid] });
  assert.equal(plan.offsetAmount, 0);
});
await t('הזמנה ישנה שהוחזרה מחוץ למערכת (עודף בספרים, בלי בקשה אוטומטית ממתינה) לא נחשבת זיכוי', () => {
  const legacy = { ...ord(1, 100), payments: [{ amount: 200 }], refunds: [{ ...autoRefund(1, 100), isExecuted: true }] };
  assert.equal(orderOpenCredit(legacy), null);
  const none = { ...ord(1, 100), payments: [{ amount: 200 }], refunds: [] };
  assert.equal(orderOpenCredit(none), null);
});
await t('זיכוי של הזמנה מחוקה לא נכלל (ברירת מחדל)', () => {
  const deleted = { ...ord(1, 100), isDeleted: true, payments: [{ amount: 200 }], refunds: [autoRefund(1, 100)] };
  const plan = planCreditOffset({ target: { ...ord(2, 80), payments: [], refunds: [] }, others: [deleted] });
  assert.equal(plan.offsetAmount, 0);
  assert.deepEqual(plan.excluded, [{ orderId: 1, reason: 'הזמנה מחוקה' }]);
});
await t('שני זיכויים: מהישן לחדש (לפי תאריך הזמנה, לא לפי סדר הרשימה)', () => {
  const older = { ...ord(7, 100), orderDate: '2026-08-01T08:00:00Z', payments: [{ amount: 140 }], refunds: [autoRefund(7, 40)] };
  const newer = { ...ord(5, 100), orderDate: '2026-09-20T08:00:00Z', payments: [{ amount: 170 }], refunds: [autoRefund(5, 70)] };
  const plan = planCreditOffset({ target: { ...ord(9, 100), payments: [], refunds: [] }, others: [newer, older] });
  assert.deepEqual(plan.sources.map((s) => [s.orderId, s.amount]), [[7, 40], [5, 60]]);
  assert.equal(plan.offsetAmount, 100);
  assert.equal(plan.available, 110);
});
await t('בקשת זיכוי ידנית פתוחה לא מקוזזת; אותה לקוחה בלבד; לא ההזמנה עצמה; תקרת maxAmount', () => {
  const manual = { ...ord(1, 100), payments: [{ amount: 200 }], refunds: [autoRefund(1, 40), { id: 'm', orderId: 1, amount: 60, isAutoGenerated: false }] };
  assert.equal(orderOpenCredit(manual).amount, 40);
  const other = { ...ord(3, 100), customerId: 'c2', payments: [{ amount: 200 }], refunds: [autoRefund(3, 100)] };
  const self = { ...ord(9, 100), payments: [{ amount: 200 }], refunds: [autoRefund(9, 100)] };
  const plan = planCreditOffset({ target: { ...ord(9, 100), payments: [], refunds: [] }, others: [manual, other, self], maxAmount: 25 });
  assert.deepEqual(plan.sources.map((s) => [s.orderId, s.amount]), [[1, 25]]);
  assert.equal(plan.offsetAmount, 25);
});
await t('חוב: הקטן משתי הנוסחאות, ולעולם לא שלילי; הזמנה מחוקה/ללא לקוחה = אין תכנית', () => {
  assert.equal(orderDebt({ totalAmount: 100, obligations: [{ amount: 80 }], payments: [{ amount: 10 }] }), 70);
  assert.equal(orderDebt({ totalAmount: 100, obligations: [{ amount: 100 }], payments: [{ amount: 120 }] }), 0);
  assert.equal(planCreditOffset({ target: { ...ord(2, 50), isDeleted: true, payments: [], refunds: [] }, others: [] }).offsetAmount, 0);
  assert.equal(planCreditOffset({ target: { orderId: 2, customerId: null, obligations: [{ amount: 50 }], payments: [], refunds: [] }, others: [] }).offsetAmount, 0);
});
await t('נוסח השאלה: שאלה אחת עם הסכום וההזמנה; שורת פירוט רק כשהסכום המקוזז שונה מהזיכוי/החוב', () => {
  const full = { available: 90, debt: 90, offsetAmount: 90, sources: [{ orderId: 12, amount: 90 }] };
  assert.equal(offsetQuestion(full), 'ללקוחה יש זיכוי פתוח של ₪90 מהזמנה #12. לקזז מהחוב?');
  const partial = offsetQuestion({ available: 90, debt: 180, offsetAmount: 90, sources: [{ orderId: 12, amount: 90 }] });
  assert.ok(partial.includes('ויישארו לתשלום ₪90'));
  const remainder = offsetQuestion({ available: 150, debt: 60, offsetAmount: 60, sources: [{ orderId: 12, amount: 60 }] });
  assert.ok(remainder.includes('היתרה תישאר זיכוי פתוח לפעם הבאה'));
  assert.ok(offsetQuestion({ available: 110, debt: 100, offsetAmount: 100, sources: [{ orderId: 7, amount: 40 }, { orderId: 5, amount: 60 }] }).includes('מהזמנות #7, #5'));
  assert.equal(offsetQuestion({ offsetAmount: 0 }), '');
});
await t('שורות התשלום: זוג הפוך באותו סכום, אותו אמצעי ייעודי, בלי isRefund (סכום האמצעי = 0), סימון זוג בהערה', () => {
  const rows = buildOffsetRows({ plan: { sources: [{ orderId: 1, amount: 90 }] }, target: { orderId: 2, customerId: 'c1' }, requestKey: 'abcd1234efgh' });
  assert.equal(rows.length, 2);
  assert.deepEqual(rows.map((r) => [r.orderId, r.amount, r.paymentMethod, r.isRefund]), [[2, 90, CREDIT_OFFSET_METHOD, false], [1, -90, CREDIT_OFFSET_METHOD, false]]);
  assert.equal(CREDIT_OFFSET_METHOD, 'קיזוז זיכוי');
  assert.equal(parsePairKey(rows[0].notes), pairKeyOf('abcd1234efgh', 1));
  assert.equal(parsePairKey(rows[1].notes), pairKeyOf('abcd1234efgh', 1));
  assert.ok(isValidRequestKey('abcd1234efgh') && !isValidRequestKey('x') && !isValidRequestKey('a b c d e f g h'));
});

console.log('lib/creditOffsetServer.js - כתיבה, סנכרון, לחיצה כפולה, מרוץ, ביטול');
await t('קיזוז מלא: שני תשלומים הפוכים, חוב אפס, בקשת הזיכוי של ההזמנה הישנה נמחקת', async () => {
  const db = scenario({ debt: 150, credit: 150 });
  const r = await apply(db, 2, { requestKey: 'req-0000001' });
  assert.equal(r.status, 'applied');
  assert.equal(r.amount, 150);
  assert.equal(paidOf(db, 2), 150);
  assert.equal(paidOf(db, 1), 100);
  assert.equal(openAuto(db, 1).length, 0, 'הבקשה הממתינה נמחקה');
  assert.equal(openAuto(db, 2).length, 0, 'אין בקשת זיכוי בהזמנה החדשה');
  assert.equal(db.txCount, 1, 'טרנזקציה אחת');
  assert.deepEqual(db.lockCalls.map((s) => s.replace(/\s+/g, ' ')), ['SELECT pg_advisory_xact_lock(7314, 1)', 'SELECT pg_advisory_xact_lock(7314, 2)'], 'נעילות בסדר עולה');
});
await t('קיזוז חלקי: הבקשה הממתינה קטנה, החוב מצטמצם, ההזמנה החדשה לא נהיית יתרת זכות', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  const r = await apply(db, 2, { requestKey: 'req-0000002' });
  assert.equal(r.amount, 90);
  assert.equal(paidOf(db, 2), 90);
  assert.equal(openAuto(db, 1).length, 0);
  assert.equal(180 - paidOf(db, 2), 90, 'נשאר חוב לתשלום');
});
await t('הזיכוי גדול מהחוב: היתרה נשארת כבקשת זיכוי ממתינה קטנה', async () => {
  const db = scenario({ debt: 60, credit: 150 });
  const r = await apply(db, 2, { requestKey: 'req-0000003' });
  assert.equal(r.amount, 60);
  assert.equal(paidOf(db, 2), 60);
  assert.deepEqual(openAuto(db, 1).map((x) => x.amount), [90]);
});
await t('שני זיכויים: נצרכים מהישן לחדש בטרנזקציה אחת, ארבע שורות', async () => {
  const db = makeDb({
    orders: [ord(7, 100, { orderDate: '2026-08-01T08:00:00Z' }), ord(5, 100, { orderDate: '2026-09-20T08:00:00Z' }), ord(9, 100)],
    payments: [pay(7, 140), pay(5, 170)],
    refunds: [autoRefund(7, 40), autoRefund(5, 70)],
  });
  const r = await apply(db, 9, { requestKey: 'req-0000004' });
  assert.deepEqual(r.sources.map((s) => [s.orderId, s.amount]), [[7, 40], [5, 60]]);
  assert.equal(db.payments.length, 6);
  assert.equal(db.txCount, 1);
  assert.equal(openAuto(db, 7).length, 0);
  assert.deepEqual(openAuto(db, 5).map((x) => x.amount), [10]);
  assert.deepEqual(db.lockCalls.map((s) => Number(s.match(/, (\d+)\)/)[1])), [5, 7, 9]);
});
await t('החזר שבוצע לא מקוזז; הזמנה מחוקה לא מקוזזת - לא נכתב דבר', async () => {
  const db = makeDb({
    orders: [ord(1, 100), ord(3, 100, { isDeleted: true }), ord(2, 80)],
    payments: [pay(1, 200), pay(1, -100, { isRefund: true, paymentMethod: 'החזר/זיכוי' }), pay(3, 200)],
    refunds: [{ orderId: 1, customerId: 'c1', amount: 100, isAutoGenerated: true, isExecuted: true }, autoRefund(3, 100)],
  });
  const before = db.payments.length;
  const r = await apply(db, 2, { requestKey: 'req-0000005' });
  assert.equal(r.status, 'nothing');
  assert.equal(db.payments.length, before);
  assert.equal(db.txCount, 0);
});
await t('לחיצה כפולה (אותו requestKey): הקריאה השנייה לא מקזזת שוב', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  const first = await apply(db, 2, { requestKey: 'req-dbl-0001' });
  const second = await apply(db, 2, { requestKey: 'req-dbl-0001' });
  assert.equal(first.status, 'applied');
  assert.equal(second.status, 'duplicate');
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 2);
  assert.equal(paidOf(db, 2), 90);
});
await t('קריאה חוזרת בלי requestKey: אין עוד זיכוי פתוח, לכן אין קיזוז נוסף', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  await apply(db, 2);
  const again = await apply(db, 2);
  assert.equal(again.status, 'nothing');
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 2);
});
await t('שתי קריאות בו-זמניות (אותו requestKey): אחת מקזזת, השנייה duplicate; מפתחות שונים: השנייה stale', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  const [a, b] = await Promise.all([apply(db, 2, { requestKey: 'req-race-0001' }), apply(db, 2, { requestKey: 'req-race-0001' })]);
  assert.deepEqual([a.status, b.status].sort(), ['applied', 'duplicate']);
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 2);
  const db2 = scenario({ debt: 180, credit: 90 });
  const [c, d] = await Promise.all([apply(db2, 2, { requestKey: 'req-race-0002' }), apply(db2, 2, { requestKey: 'req-race-0003' })]);
  assert.deepEqual([c.status, d.status].sort(), ['applied', 'stale']);
  assert.equal(db2.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 2);
});
await t('כישלון באמצע הכתיבה: הכל מתגלגל אחורה (אין חצי זוג), ולא מסנכרנים', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  db.failOnCreate = 2; // הצד השני של הזוג נכשל
  let synced = 0;
  await assert.rejects(() => applyCreditOffset({ prisma: db.client, orderId: 2, requestKey: 'req-fail-0001', syncPendingCreditRefund: async () => { synced++; } }), /boom/);
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 0);
  assert.equal(synced, 0);
  assert.equal(openAuto(db, 1).length, 1, 'הבקשה הממתינה נשארה');
});
await t('תשלום מקביל בהזמנה בין הטעינה לכתיבה: stale ולא כותבים', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  const orig = db.client.payment.aggregate;
  db.client.payment.aggregate = async (args) => { db.payments.push({ id: `px${++seq}`, orderId: 2, customerId: 'c1', amount: 20, isDeleted: false, isRefund: false, paymentMethod: 'מזומן', notes: '' }); db.client.payment.aggregate = orig; return orig(args); };
  const r = await apply(db, 2, { requestKey: 'req-stale-001' });
  assert.equal(r.status, 'stale');
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 0);
});
await t('לוח הבקרה והמזומן לא מושפעים: סכום כל התשלומים זהה, "מזומן" זהה, ופרוסת "קיזוז זיכוי" מסתכמת לאפס', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  db.payments.push({ id: `p${++seq}`, isDeleted: false, isRefund: false, notes: '', ...pay(2, 40, { paymentMethod: 'מזומן' }) });
  const totals = () => {
    const live = db.payments.filter((p) => !p.isDeleted);
    const byMethod = {};
    for (const p of live.filter((x) => !x.isRefund)) byMethod[p.paymentMethod] = round2((byMethod[p.paymentMethod] || 0) + p.amount); // כמו app/dashboard/page.js: groupBy עם isRefund:false
    return { net: round2(live.reduce((s, p) => s + p.amount, 0)), byMethod };
  };
  const before = totals();
  await apply(db, 2, { requestKey: 'req-cash-0001' });
  const after = totals();
  assert.equal(after.net, before.net, 'הסכום הכולל זהה');
  assert.equal(after.byMethod['מזומן'], before.byMethod['מזומן'], 'מזומן זהה');
  assert.equal(after.byMethod[CREDIT_OFFSET_METHOD], 0, 'הקיזוז מתקזז לאפס בכל פרוסה');
  assert.ok(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).every((p) => p.isRefund === false));
});
await t('מחיקת ההזמנה שקוזז לתוכה: תנועות הפוכות מחזירות את הזיכוי להזמנה המקורית; פעם שנייה לא עושה כלום', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  await apply(db, 2, { requestKey: 'req-rev-00001' });
  assert.equal(openAuto(db, 1).length, 0);
  const rev = await reverseCreditOffsetsForOrder({ prisma: db.client, orderId: 2, syncPendingCreditRefund: db.sync });
  assert.equal(rev.reversed, 1);
  assert.equal(paidOf(db, 1), 190, 'ההזמנה הישנה חזרה למצב שלפני הקיזוז');
  assert.deepEqual(openAuto(db, 1).map((x) => x.amount), [90], 'הבקשה הממתינה חזרה');
  assert.equal(paidOf(db, 2), 0);
  const again = await reverseCreditOffsetsForOrder({ prisma: db.client, orderId: 2, syncPendingCreditRefund: db.sync });
  assert.equal(again.reversed, 0);
  assert.equal(db.payments.filter((p) => p.paymentMethod === CREDIT_OFFSET_METHOD).length, 4, 'ארבע שורות בסך הכל, לא נמחקו תשלומים');
  const none = await reverseCreditOffsetsForOrder({ prisma: makeDb({ orders: [ord(2, 10)] }).client, orderId: 2, syncPendingCreditRefund: async () => { throw new Error('should not sync'); } });
  assert.equal(none.reversed, 0);
});
await t('ביטול פריטים (לא מחיקה): הכסף שקוזז הופך לבקשת זיכוי בהזמנה החדשה כמו כל תשלום - לא נדרש ביטול קיזוז', async () => {
  const db = scenario({ debt: 90, credit: 90 });
  await apply(db, 2, { requestKey: 'req-cancel-001' });
  db.orders.find((o) => o.orderId === 2).obligations = []; // כל הפריטים בוטלו
  await db.sync(2);
  assert.deepEqual(openAuto(db, 2).map((x) => x.amount), [90]);
});
await t('previewCreditOffset: קריאה בלבד - אין כתיבה', async () => {
  const db = scenario({ debt: 180, credit: 90 });
  const r = await previewCreditOffset(db.client, 2);
  assert.equal(r.plan.offsetAmount, 90);
  assert.equal(db.txCount, 0);
  assert.equal(db.creates, 0);
});

console.log('lib/creditOfferClient.js - השאלה והבקשה');
const fakeClient = ({ plan, post = { ok: true, status: 200, body: { status: 'applied', amount: 90 } }, yes = true } = {}) => {
  const calls = { fetch: [], confirm: [], approve: 0, say: [] };
  const fetchImpl = async (url, init) => {
    calls.fetch.push([url, init]);
    if (!init) return { ok: true, status: 200, json: async () => plan };
    return { ok: post.ok, status: post.status, json: async () => post.body, clone() { return this; } };
  };
  const sendWithApproval = async (send) => { calls.approve++; return send({ approvalToken: 'tok' }); };
  return { calls, args: { orderId: 2, confirm: async (m) => { calls.confirm.push(m); return yes; }, sendWithApproval, fetchImpl, notify: (m) => calls.say.push(m), newKey: () => 'key-fixed-0001' } };
};
const PLAN = { enabled: true, offsetAmount: 90, question: 'ללקוחה יש זיכוי פתוח של ₪90 מהזמנה #1. לקזז מהחוב?' };
await t('כבוי / אין זיכוי: לא שואלים ולא כותבים', async () => {
  for (const plan of [{ enabled: false, offsetAmount: 0 }, { enabled: true, offsetAmount: 0 }]) {
    const { calls, args } = fakeClient({ plan });
    assert.deepEqual(await offerCreditOffset(args), { status: 'none' });
    assert.equal(calls.confirm.length, 0);
    assert.equal(calls.fetch.length, 1);
  }
});
await t('שגיאת רשת בבדיקה: ממשיכים כרגיל (none), לא זורקים', async () => {
  const args = { orderId: 2, confirm: async () => true, sendWithApproval: async () => { throw new Error('x'); }, fetchImpl: async () => { throw new Error('offline'); } };
  assert.deepEqual(await offerCreditOffset(args), { status: 'none' });
});
await t('"לא": שואלים בדיוק פעם אחת ולא שולחים POST', async () => {
  const { calls, args } = fakeClient({ plan: PLAN, yes: false });
  assert.deepEqual(await offerCreditOffset(args), { status: 'declined' });
  assert.deepEqual(calls.confirm, [PLAN.question]);
  assert.equal(calls.fetch.length, 1);
});
await t('"כן": POST אחד עם maxAmount וה-requestKey, דרך חלון המאשר (sendWithApproval, סוג manual_payment_credit)', async () => {
  const { calls, args } = fakeClient({ plan: PLAN });
  assert.deepEqual(await offerCreditOffset(args), { status: 'applied', amount: 90 });
  assert.equal(calls.fetch.length, 2);
  const [url, init] = calls.fetch[1];
  assert.equal(url, '/api/orders/2/credit-offset');
  assert.equal(init.method, 'POST');
  assert.deepEqual(JSON.parse(init.body), { maxAmount: 90, requestKey: 'key-fixed-0001', approvalToken: 'tok' });
  assert.equal(calls.approve, 1);
});
await t('ביטול חלון המאשר (403) = cancelled; שגיאת שרת = error עם הודעה; duplicate נחשב applied', async () => {
  let f = fakeClient({ plan: PLAN, post: { ok: false, status: 403, body: { error: 'x' } } });
  assert.deepEqual(await offerCreditOffset(f.args), { status: 'cancelled' });
  f = fakeClient({ plan: PLAN, post: { ok: false, status: 500, body: { error: 'שגיאה ברישום הקיזוז' } } });
  assert.deepEqual(await offerCreditOffset(f.args), { status: 'error' });
  assert.deepEqual(f.calls.say, ['שגיאה ברישום הקיזוז']);
  f = fakeClient({ plan: PLAN, post: { ok: true, status: 200, body: { status: 'duplicate', amount: 0 } } });
  assert.equal((await offerCreditOffset(f.args)).status, 'applied');
});

console.log('מבנה: ברירת מחדל כבויה, נתיב, מחיקה, הדפים הישנים, הגדרה, seed');
await t('ההגדרה customer_credit_offset_prompt: שם+הסבר בעברית, מפתח בוליאני, ב-SimLayout; ברירת מחדל = שורה חסרה = כבוי', () => {
  assert.equal(CREDIT_OFFSET_SETTING, 'customer_credit_offset_prompt');
  const meta = read('lib/settingsMetadata.js');
  assert.ok(/customer_credit_offset_prompt: 'שאלת קיזוז זיכוי פתוח מחוב חדש'/.test(meta));
  assert.ok(/customer_credit_offset_prompt: 'כשמופעל[^']*כבוי \(ברירת מחדל\)/.test(meta));
  assert.ok(/SETTINGS_BOOLEAN_KEYS[\s\S]*'customer_credit_offset_prompt'/.test(meta));
  assert.ok(read('lib/settingsSimLayout.js').includes("'customer_credit_offset_prompt'"));
  const route = read('app/api/orders/[id]/credit-offset/route.js');
  assert.ok(/String\(row\.value\)\.trim\(\)\.toLowerCase\(\) === 'true'/.test(route) && /return false; \/\/ כמו שורה חסרה/.test(route), 'חסר/שגיאה = כבוי');
  assert.ok(/enabled: false, offsetAmount: 0/.test(route) && /status: 404/.test(route), 'כבוי: GET ריק, POST 404');
  assert.ok(/CREDIT_OFFSET_SETTING/.test(route));
});
await t('הנתיב: מאשר נאכף תמיד (permissionsEnforced:true, manual_payment_credit), אסימון נצרך רק בהצלחה, בלי AuditLog ידני, בלי קריאות כבדות בטרנזקציה', () => {
  const route = read('app/api/orders/[id]/credit-offset/route.js');
  assert.ok(/KINDS\.MANUAL_PAYMENT_CREDIT/.test(route) && /permissionsEnforced: true/.test(route));
  assert.ok(/commitApprovalClaims\(claims\)/.test(route) && /releaseApprovalClaims\(claims\)/.test(route));
  assert.ok(!/auditLog[.]/i.test(route) && !/auditLog[.]/i.test(read('lib/creditOffsetServer.js')));
  const srv = read('lib/creditOffsetServer.js');
  const tx = srv.slice(srv.indexOf('prisma.$transaction(async (tx) => {'), srv.indexOf('}, TX_OPTIONS);'));
  assert.ok(!/findMany|findUnique|include:/.test(tx), 'בתוך הטרנזקציה: נעילה + סכומים + כתיבות בלבד');
  assert.ok(/for \(const data of rows\) await tx\.payment\.create\(\{ data \}\)/.test(tx));
});
await t('מחיקת הזמנה קוראת לביטול הקיזוז (לא מפיל את המחיקה); הכרטיס הישן מגודר בהגדרה ושואל אחרי שמירה/יציאה; האשף הישן אחרי יצירה', () => {
  const del = read('app/api/orders/[id]/route.js');
  assert.ok(/reverseCreditOffsetsForOrder\(\{ prisma, orderId: parsedOrderId, syncPendingCreditRefund \}\)/.test(del));
  const card = read('app/orders/[id]/LegacyOrderPage.js');
  assert.ok(/useState\(false\);\n {2}useEffect/.test(card) && /key === 'customer_credit_offset_prompt'/.test(card) && /creditOffsetSetting\.value === 'true'/.test(card));
  assert.equal((card.match(/askCreditOffset\(updatedOrder\.orderId\)/g) || []).length, 2, 'handleSave + handleExit');
  assert.equal((card.match(/creditOffsetPromptEnabled && freshDebtNow > 0 && freshDebtNow > openedDebtRounded \+ 0\.01/g) || []).length, 2);
  assert.ok(/if \(!creditOffsetPromptEnabled \|\| !orderIdNow\) return \{ status: 'none' \};/.test(card), 'כבוי = אפס בקשות');
  const wiz = read('app/orders/new/LegacyNewOrderPage.js');
  assert.ok(/settings\.customer_credit_offset_prompt === 'true' && data\.orderId/.test(wiz));
});
await t('לא נגעו בקבצי a5 (כרטיס הזמנה חדש / אשף חדש)', () => {
  for (const f of ['app/components/order-card', 'app/components/new-order']) {
    const walk = (d) => fs.readdirSync(path.join(ROOT, d), { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(`${d}/${e.name}`) : [`${d}/${e.name}`]));
    for (const file of walk(f)) assert.ok(!/credit-offset|creditOffset|customer_credit_offset_prompt/.test(read(file)), file);
  }
});
await t('סקריפט seed: דרייראן כברירת מחדל, org2=true, בדיקת host דרך העזר המשותף', () => {
  const s = read('scripts/seed_customer_credit_offset_prompt_setting.js');
  assert.ok(/key: 'customer_credit_offset_prompt'/.test(s) && /trueForOrg: 2/.test(s) && /seedBoolSetting\(/.test(s));
  assert.ok(!/--write/.test(s.split('\n').filter((l) => !l.startsWith('//')).join('\n')), 'הכתיבה רק דרך העזר המשותף (--write מפורש)');
  const helper = read('scripts/lib/seed-bool-setting.js');
  assert.ok(/SAFETY ABORT/.test(helper) && /--write/.test(helper));
});
await t('היסטוריית ההזמנה: ניסוח ייעודי לתשלום קיזוז (לא "הוחזר ללקוח")', () => {
  const h = read('lib/history/orderHistory.js');
  assert.ok(/m === CREDIT_OFFSET_METHOD && amount !== null && amount !== 0/.test(h) && /זיכוי פתוח קוזז לטובת הזמנה אחרת/.test(h));
});

console.log(`\n${passed} passed, ${failed} failed`);
if (failed) process.exit(1);
